[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mcuhex-sdk"
dynamic = ["version"]
requires-python = ">=3.8"

[tool.setuptools]
py-modules = ["server"]

[tool.setuptools.dynamic]
version = { attr = "desktop.config.VERSION" }

[tool.setuptools.packages.find]
include = ["probe*", "desktop*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
